import type { SubcommandDefinition } from '@src/system/command-definition';

export const listDefinition = (
  prefix: string,
  alias: string,
): SubcommandDefinition => ({
  name: 'list',
  summary: 'List local bookmarks; optional filters and category tree view.',
  aliases: [],
  arguments: [],
  options: [
    {
      name: 'by',
      summary: 'Group results (cats = category tree).',
      flag: '--by',
      shortFlag: '-b',
      kind: 'string',
      choices: ['cats'],
      webDefaultValue: 'cats',
    },
    {
      name: 'queued',
      summary: 'Only bookmarks in the queue.',
      flag: '--queued',
      shortFlag: null,
      kind: 'boolean',
    },
    {
      name: 'no-queued',
      summary: 'Only bookmarks not in the queue.',
      flag: '--no-queued',
      shortFlag: null,
      kind: 'boolean',
    },
    {
      name: 'unconsumed',
      summary: 'Only unconsumed bookmarks.',
      flag: '--unconsumed',
      shortFlag: null,
      kind: 'boolean',
    },
    {
      name: 'consumed',
      summary: 'Only consumed bookmarks.',
      flag: '--consumed',
      shortFlag: null,
      kind: 'boolean',
    },
    {
      name: 'type',
      summary: 'Media type filter.',
      flag: '--type',
      shortFlag: null,
      kind: 'string',
    },
    {
      name: 'media_types',
      summary: 'Show only these media types (repeatable or comma-separated).',
      flag: '--media_types',
      shortFlag: null,
      kind: 'string',
      multiple: true,
    },
    {
      name: 'tag',
      summary: 'Tag filter (repeatable in CLI).',
      flag: '--tag',
      shortFlag: null,
      kind: 'string',
    },
    {
      name: 'tags',
      summary: 'Comma-separated tags (all required).',
      flag: '--tags',
      shortFlag: null,
      kind: 'string',
    },
    {
      name: 'category',
      summary: 'Category path filter.',
      flag: '--category',
      shortFlag: null,
      kind: 'string',
    },
    {
      name: 'title',
      summary: 'Title substring filter.',
      flag: '--title',
      shortFlag: null,
      kind: 'string',
    },
    {
      name: 'url',
      summary: 'URL substring filter.',
      flag: '--url',
      shortFlag: null,
      kind: 'string',
    },
  ],
  examples: [
    `${prefix}${alias} list`,
    `${prefix}${alias} list --by cats`,
    `${prefix}${alias} list --unconsumed --tag rust`,
  ],
  webWidget: {
    placement: 'header',
    surface: 'timeline_singleton',
    label: 'BM',
    modalTitle: 'Bookmarks list',
    icon: '/plugins/bm/commands/list/renderers/list.svg',
    order: 25,
  },
});
